name: Deploy
on:
  push:
    branches:
      - master
permissions:
  contents: write
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Docker image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_PAT }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx/cache
          key: ${{ runner.os }}-buildx-cache-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-cache-

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push images
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          cache-from: type=local,src=/tmp/.buildx/cache
          cache-to: type=local,dest=/tmp/.buildx/cache
          tags: |
            ghcr.io/mikabot/cluster-operator:latest

  deploy:
    name: Deploy
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Kubernetes workflow
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBECONFIG }}" >> ~/.kube/config

      - name: Set images
        run: |
          kubectl set image deployment/beta-operator beta-operator=ghcr.io/mikabot/cluster-operator:latest
          kubectl set image deployment/premium-operator premium-operator=ghcr.io/mikabot/cluster-operator:latest
          kubectl set image deployment/main-operator main-operator=ghcr.io/mikabot/cluster-operator:latest

      - name: Rollout status
        run: |
          kubectl rollout status deployment/beta-operator
          kubectl rollout status deployment/premium-operator
          kubectl rollout status deployment/main-operator
